
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Escritorio/Cloud/FinalProject-master/config-server
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000
